config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :about, only: [:index]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :create, :new, :destroy]
    resources :sales, only: [:index, :new, :destroy, :create]
    resources :orders, only: [:index, :show]
  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true
 
  after_create do
    items = LineItem.where(order_id: id).all
    items.each do |item|
      product = Product.find(item.product_id)
      product.update(quantity: reduce_stock(product, item.quantity))
    end
  end

  private

  def reduce_stock(product, quantity)
    product.quantity.to_i - quantity
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all
  end

  def show
    @items = LineItem.joins(:product).where({order_id: params[:id]}).select(:order_id, :product_id, :name, :quantity, :item_price_cents, :total_price_cents)
    @order = Order.find(params[:id])
  end

  def discount?(cost_price, paid_price)
    if cost_price.instance_of? (Array)
      total_cost = cost_price.reduce(0) { |sum, n| sum + n}
      return total_cost - paid_price.to_i
    else
    return cost_price - paid_price.to_i
  end
end
helper_method :discount?

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      get_discount_price?(cart_subtotal_cents).to_i,
      description: current_user ? "#{current_user.name}'s Jungle Order" : "Guest's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: get_discount_price?(cart_subtotal_cents).to_i,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: get_discount_price?(product.price * quantity).to_i,
      )
    end
    order.save!
    UserMailer.receipt_email(order).deliver_later
    order
  end


end

app/views/admin/orders/_order.html.erb
<tr>
  <td>
   <%= link_to admin_order_path(order.id) do %>
    <%=order.id%>
    <% end %>
  </td>
  <td>
    <%= humanized_money_with_symbol order.total_cents / 100 %>
  </td>
  <td>
    <%=order.email%>
  </td>
</tr>

app/views/admin/orders/index.html.erb
<section class="admin-orders-index">

  <header class="page-header">
    <h1>Admin &raquo; All Orders</h1>
  </header>

  <div class="panel panel-default orders">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>Total</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody>
        <%=render @orders %>
      </tbody>
    </table>
  </div>

</section>

app/views/admin/orders/show.html.erb
<section class="orders-show">
<%#raise @items.inspect%>

  <header class="page-header">
    <h1>Admin &raquo; All Orders &raquo; Order #<%=@items[0]['order_id']%></h1>
  </header>
 <h4><%=@order.email%></h4>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Product ID</th>
          <th>Product Name</th>
          <th>Quantity</th>
          <th>Item Price</th>
          <th>Discount</th>
          <th>Total Paid</th>
        </tr>
      </thead>
      <tbody>
      <%@items.each do |item|%>
      <tr>
      <%#raise @items.inspect%>
        <td>
          <%=item.product_id%>
        </td>
         <td>
          <%=item.name%>
        </td>
        <td>
          <%=item.quantity%>
        </td>
        <td>
          <%=humanized_money_with_symbol item.item_price_cents / 100%>
        </td>
         <td>
          <%=humanized_money_with_symbol discount?((item.item_price_cents * item.quantity), item.total_price_cents) / 100%>
        </td>
        <td>
          <%=humanized_money_with_symbol item.total_price_cents / 100%>
        </td>
        </tr>
        <%end%>
      </tbody>
      <tfoot>
        <th colspan="4">
            TOTAL:
          </th>
          <th>
          <%= humanized_money_with_symbol discount?(@items.map {|item| item.item_price_cents * item.quantity }, @order.total_cents) / 100%>
          </th>
          <th>
          <%= humanized_money_with_symbol @order.total_cents / 100%>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

</section>